export function trackedFiles(root: string, pathspec?: string): string[];
export function trackedDocs(root: string): string[];
export function specDocs(root: string): string[];
export const COMMENTED_EXTENSIONS: readonly string[];
export function trackedRefSources(root: string): string[];
export function isProseData(rel: string): boolean;
export function isVerbatimRecord(rel: string): boolean;
export function isPendingDecision(rel: string): boolean;
export function isRefRuleExempt(rel: string): boolean;
export function refProseOf(rel: string, text: string): string;
export function historyDocs(root: string): Set<string>;
export function historyRuleSources(root: string): string[];
export function isAnalysisRecord(rel: string): boolean;
export function isMarkRuleDoc(rel: string): boolean;
