import { describe, expect, it } from 'vitest';

import { DEFAULT_BODY, run } from '../support/mergeAndCloseWorld';

/**
 * PR本文とレビューのコメントから `## ユーザーへ` を拾い、ユーザーへ ラベルと `RELAY` の行を出すところ。
 *
 * 世界の組み方と、ファイルを分けてある理由は `tests/support/mergeAndCloseWorld.ts`。
 */

describe('merge-and-close.sh の `## ユーザーへ` の中継', () => {
  // 印を置くだけ。下ろす側はまだ無いので、ラベルが滞留を見せ続ける（board-design 3.2）。
  it('本文に `## ユーザーへ` があれば、ユーザーへ ラベルを付けて RELAY を出す', () => {
    const result = run({ body: `${DEFAULT_BODY}\n\n## ユーザーへ\n\n- #1353 を立てた（範囲外）\n` });

    expect(result.lines).toContain('RELAY 1000');
    expect(result.labels).toContain('--add-label ユーザーへ');
  });

  // 「回されたものが無い」と「読み落とした」を、ユーザーが区別できなくなる。
  it('節が無ければ、ラベルも RELAY も出さない', () => {
    const result = run({ body: `${DEFAULT_BODY}\n\n## 案\n\n- 積ではなく加算で表す\n` });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // 書く口はPR本文とレビューのコメントの2つある（`review-prompt.md`）。読む口が1つだと、
  // レビューが回したものだけが黙って落ちる。**本文には節が無い世界で見る。**
  it('レビューのコメントの `## ユーザーへ` も拾う', () => {
    const result = run({
      comments: [
        '[レビュー] 通してよい\n\n## ユーザーへ\n\n- `parseActiveEffects.ts` の doc に同じ誤りが残っている\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n',
      ],
    });

    expect(result.lines).toContain('RELAY 1000');
    expect(result.labels).toContain('--add-label ユーザーへ');
  });

  // 回す側はレビューだけ。デーモンの指示やユーザー自身の書き込みを拾うと、下ろす相手の居ない印が残る。
  it('`[レビュー]` で始まらないコメントの節は拾わない', () => {
    const result = run({
      comments: ['[デーモン] 直し待ちにします。\n\n## ユーザーへ\n\n- これは回す側ではない\n'],
    });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // `## 仮決め` は「なし」と書かせる規約なので、書く側は取り違える。中身の無い印が残ると `RELAY` が
  // 毎周出て、合図が1件でも出た見張りはそこで終わる（他の待ちに使えなくなる）。
  it('節はあっても中身が「なし」なら、ラベルも RELAY も出さない', () => {
    const result = run({
      body: `${DEFAULT_BODY}\n\n## ユーザーへ\n\nなし（この変更自体が盤面の道具への直し）。\n`,
    });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // 節を閉じるのが `##` の見出しだけだと、**本文の末尾に置かれた節がレビューのコメントへ伸びる**。
  // レビュー側はこの節をコメントの末尾に置く（`review-prompt.md`）ので、これは常に起きる。
  it('本文の末尾の節が「なし」なら、レビューのコメントが付いていてもラベルを付けない', () => {
    const result = run({
      body: `${DEFAULT_BODY}\n\n## ユーザーへ\n\nなし（この変更自体が盤面の道具への直し）。\n`,
      comments: ['[レビュー] 通してよい\n\n本文の実測は自分でも数え直して一致した。\n'],
    });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // レビューのコメントには Claude Code の署名（`---` と `_Generated by …_`）が必ず付く。節の後ろに
  // 常に続くので、署名を節の中身と数えると**レビュー側では「なし」の判定が一度も働かない**。
  it('レビューが「なし」と書いたら、後ろに署名が続いてもラベルを付けない', () => {
    const result = run({
      comments: [
        '[レビュー] 通してよい\n\n## ユーザーへ\n\nなし。\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n',
      ],
    });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // コメントどうしの境目も同じ。1本に繋いで読むと、末尾に節を置いたコメントの節が次のコメントへ
  // 伸びる。繋ぎ目の綴りで塞ぐ形だと、綴りが片側だけずれてもここが緑のまま通ってしまう。
  it('コメントの末尾の節が「なし」なら、後ろに別のコメントが続いてもラベルを付けない', () => {
    const result = run({
      comments: [
        '[レビュー] 通してよい\n\n## ユーザーへ\n\nなし。\n',
        '[レビュー] 通してよい\n\n差分を読み直したが、他に直すところは無い。\n',
      ],
    });

    expect(result.lines.some((line) => line.startsWith('RELAY '))).toBe(false);
    expect(result.labels.some((label) => label.includes('ユーザーへ'))).toBe(false);
  });

  // 1件ずつ読むので、読み落とせば**後ろのコメントだけ**が黙って落ちる。
  it('2件目以降のレビューのコメントの `## ユーザーへ` も拾う', () => {
    const result = run({
      comments: [
        '[レビュー] 通してよい\n\n## ユーザーへ\n\nなし。\n',
        '[レビュー] 通してよい\n\n## ユーザーへ\n\n- #1353 を立てた（範囲外）\n',
      ],
    });

    expect(result.lines).toContain('RELAY 1000');
    expect(result.labels).toContain('--add-label ユーザーへ');
  });

  // マージは済んでいるので、印を置けなかっただけで後片付け（`main` の追随）ごと落としてはいけない。
  it('印を置けなくても止まらず、後片付けを済ませてから残りとして報せる', () => {
    const result = run({
      body: `${DEFAULT_BODY}\n\n## ユーザーへ\n\n- #1353 を立てた（範囲外）\n`,
      labelFails: true,
    });

    expect(result.lines).toContain('UNRELAYED 1000');
    expect(result.lines.some((line) => line.startsWith('SYNCED '))).toBe(true);
    expect(result.status).toBe(2);
  });
});
